-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 23:28:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bespoke
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bespoke
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bespoke` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bespoke` ;

-- -----------------------------------------------------
-- Table `bespoke`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bespoke`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bespoke`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bespoke`.`product` (
  `name` VARCHAR(255) NOT NULL,
  `qty` INT NOT NULL,
  `commission_percentage` FLOAT NULL DEFAULT NULL,
  `manufacturer` VARCHAR(255) NOT NULL,
  `purchase_price` FLOAT NOT NULL,
  `sale_price` FLOAT NOT NULL,
  `style` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bespoke`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bespoke`.`discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(45) NOT NULL,
  `begin_date` VARCHAR(45) NOT NULL,
  `end_date` VARCHAR(45) NOT NULL,
  `discount_percentage` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_idx` (`product` ASC) VISIBLE,
  CONSTRAINT `product_discount`
    FOREIGN KEY (`product`)
    REFERENCES `bespoke`.`product` (`name`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bespoke`.`saleperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bespoke`.`saleperson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `start_date` VARCHAR(45) NULL DEFAULT NULL,
  `termination_date` VARCHAR(45) NULL DEFAULT NULL,
  `manager` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bespoke`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bespoke`.`sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(45) NOT NULL,
  `saleperson` INT NOT NULL,
  `customer` INT NOT NULL,
  `sale_date` DATE NOT NULL,
  `price` FLOAT NOT NULL,
  `commission` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `name_idx` (`product` ASC) VISIBLE,
  INDEX `saleperson_idx` (`saleperson` ASC) VISIBLE,
  INDEX `customer_idx` (`customer` ASC) VISIBLE,
  CONSTRAINT `customer`
    FOREIGN KEY (`customer`)
    REFERENCES `bespoke`.`customer` (`id`),
  CONSTRAINT `product`
    FOREIGN KEY (`product`)
    REFERENCES `bespoke`.`product` (`name`),
  CONSTRAINT `saleperson`
    FOREIGN KEY (`saleperson`)
    REFERENCES `bespoke`.`saleperson` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bespoke`.`sale_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bespoke`.`sale_info` (
  `id` INT NOT NULL,
  `commission` FLOAT NULL DEFAULT NULL,
  `customer` INT NULL DEFAULT NULL,
  `product` VARCHAR(255) NULL DEFAULT NULL,
  `sale_date` DATE NULL DEFAULT NULL,
  `sale_price` INT NULL DEFAULT NULL,
  `saleperson` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
